name: Gradle Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    environment: main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

    - name: Build & Test 1
      run: ./gradlew :lesson:module-1-lesson-1-xml-context:clean :lesson:module-1-lesson-1-xml-context:classes :lesson:module-1-lesson-1-xml-context:test

    - name: Build & Test 2
      run: ./gradlew :homework:homework-1-xml-context:clean :homework:homework-1-xml-context:classes :homework:homework-1-xml-context:test
